name: Unit Testing

on: [push, pull_request, workflow_dispatch]

jobs:
  run:
    name: Run Luau Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Luau
        uses: encodedvenom/install-luau@v2.1

      - name: Run Unit Tests
        id: run_tests
        run: |
          output=$(luau tests/tests.luau)
          echo "$output"
          # Check if any line contains the string "Error"
          if [[ "$output" == *"Error"* ]]; then
            echo "Error: One or More Unit Tests Failed."
            exit 1
          else
            echo "Unit Tests Passed"
          fi
